import type { Settings } from "./types";

export const STORAGE_KEY = "harbor.settings";

export const DEFAULT: Settings = {
  soundTheme: "none",
  sfxVolume: 50,
  playerVolumeSfx: false,
  experimentalLiquidGlassEnabled: false,
  experimentalLiquidGlassOpacity: 100,
  defaultLiquidGlassBlur: 2.5,
  defaultLiquidGlassTint: 40,
  posterBackdropExpansion: false,
  posterFocusedCard: false,
  posterDockMagnification: false,
  posterDockTransitionMs: 760,
  blurComments: false,
  blurEpisodes: false,
  tmdbKey: "",
  omdbKey: "",
  rpdbKey: "",
  imdbApiFallback: true,
  harborImdbRatings: false,
  fanartKey: "",
  tvdbKey: "",
  rdKey: "",
  tbKey: "",
  adKey: "",
  pmKey: "",
  dlKey: "",
  region: "US",
  preferredLanguages: ["English", "Spanish"],
  requirePreferredLanguage: false,
  showImdbBadge: true,
  showTmdbBadge: false,
  showRtBadge: true,
  showMalBadge: true,
  animeCardRating: "mal",
  showMetacriticBadge: false,
  showLetterboxdBadge: false,
  showMdblistBadge: false,
  showTraktBadge: false,
  showDetailRatings: true,
  showImdbDetail: true,
  showTmdbDetail: true,
  showMalDetail: true,
  showRtDetail: true,
  showRtAudienceDetail: true,
  showLetterboxdDetail: true,
  showMetacriticDetail: true,
  showTraktDetail: true,
  showMdblistDetail: true,
  showTraktComments: false,
  showSimklBadge: true,
  showDubBadge: true,
  simklShowCommunityRatings: true,
  simklEnableUserRatings: true,
  simklGranularFilters: {
    movies: {
      plantowatch: true,
    },
    shows: {
      watching: true,
      plantowatch: true,
    },
    anime: {
      watching: true,
      plantowatch: true,
    },
  },
  cardBadgeLimit: 3,
  showQualityBadge: true,
  showCardBadges: true,
  homeLanguages: [],
  posterScale: 1.15,
  posterRadius: 12,
  posterEffect: "fade",
  rowTitleScale: 1,
  playerTitleScale: 1,
  playerTitleSeriesFirst: false,
  uiScale: 0.8,
  serveWebUi: false,
  remoteControlEnabled: false,
  trailerQuality: "auto",
  detailTrailerAutoplay: false,
  heroBackdropCarousel: false,
  detailTrailerAudio: false,
  heroShadow: 100,
  heroFull: false,
  heroFullQuality: true,
  resumePrompt: true,
  resumePlayback: true,
  keepFullscreenOnExit: true,
  fullscreenRestorePosition: true,
  contentAdvisoryToast: false,
  playerVolumeHud: true,
  playerVolumeHudPosition: "center",
  customPlaybackSpeeds: [],
  customSleepMinutes: [],
  badgePlacement: "bottom",
  watchlistBadge: "bottomStart",
  showWatchedButton: true,
  showPopcornBadge: false,
  episodeLayout: "list",
  episodeSort: "oldest",
  showEpisodeRating: false,
  showEpisodeDescription: false,
  hdEpisodeImages: true,
  episodeArcGroups: false,
  episodeOrderProvider: "tvdb",
  tvdbSeasonType: "aired",
  tvdbOrderPanel: true,
  tvdbPin: "",
  harborAvatar: null,
  harborColor: "#7dd3fc",
  anilistAutoSync: true,
  malAutoSync: true,
  anilistBlurComments: false,
  showAnilistComments: false,
  useAnilistAvatar: false,
  useTraktAvatar: false,
  useSimklAvatar: false,
  useMalAvatar: false,
  traktClientId: "",
  traktClientSecret: "",
  traktAccessToken: null,
  traktRefreshToken: null,
  traktExpiresAt: 0,
  traktUsername: null,
  streaming: {
    netflix: false,
    disney: false,
    hulu: false,
    prime: false,
    apple: false,
    max: false,
    paramount: false,
    peacock: false,
    crunchyroll: false,
  },
  showAdultAddons: false,
  togetherRelayUrl: "",
  togetherCfToken: "",
  togetherCfAccountId: "",
  togetherCfDeployed: false,
  togetherShareCursors: true,
  togetherGuestsPick: false,
  discordRichPresence: true,
  discordHideTitle: false,
  discordShowWhenPaused: true,
  discordShowWhenBrowsing: true,
  discordShowPoster: true,
  discordShowTimestamp: true,
  discordShowPartyJoin: false,
  playerEngine: "auto",
  playerShellId: "default",
  playerChromeTheme: "default",
  playerMenuBlack: true,
  seekPreviewEnabled: true,
  instantPlay: true,
  seasonSourceLock: false,
  rememberLastStream: true,
  keepSourceNextEpisode: false,
  playerHdrToSdr: true,
  playerRtxHdr: false,
  playerMacEdr: false,
  playerDisplayPanel: "auto",
  playerMotionInterp: false,
  playerAnime4k: false,
  playerAnime4kAnimeOnly: true,
  playerAnime4kIndicator: false,
  playerMpvEmbed: true,
  playerP2pChip: true,
  showQualityInfo: true,
  stremioServerTranscode: false,
  directTorrentStream: true,
  torrentsDisabled: false,
  torrentFullDownload: false,
  p2pAutoConsent: false,
  streamCacheRetentionHours: 24,
  streamCacheMaxGb: 0,
  deleteWatchedDownloads: false,
  streamCacheDir: "",
  remoteStreamServerUrl: "",
  remoteStreamServerStrict: false,
  castAlwaysTranscode: true,
  playerAnime4kShaders: [],
  playerAnime4kMode: "A",
  playerAnime4kTier: "hq",
  playerAnime4kFolder: "",
  playerAnime4kOverride: "auto",
  preferredSubLangs: ["English", "Spanish"],
  preferredAudioLangs: ["English", "Spanish"],
  subFontSize: 35,
  subFontColor: "#FFFFFF",
  subBorderColor: "#000000",
  subBorderSize: 2,
  subMarginY: 12,
  subAlignX: "center",
  subAssOverride: "scale",
  subStyle: "outline",
  subFontFamily: "inter",
  subBold: true,
  customFonts: [],
  subBoxOpacity: 0.6,
  subBoxColor: "#000000",
  subOpacity: 1,
  subLineSpacing: 0,
  subProvidersEnabled: { wyzie: false, opensubtitles: true, jimaku: false, addons: true },
  subShowInPip: true,
  subtitleAutoSync: false,
  subtitlesOffByDefault: false,
  preferEmbeddedSubs: true,
  subtitleAutoUpgrade: true,
  subtitlePreselect: false,
  betaUpdates: false,
  autoSkipIntro: false,
  autoSkipRecap: false,
  autoSkipOutro: false,
  autoSkipAd: false,
  showSkipButton: true,
  skipButtonHideSec: 10,
  trackBlockWords: ["commentary"],
  forcedSubsWhenNativeAudio: false,
  tmdbLanguage: "",
  tmdbImageLangs: ["English", "Original"],
  nfoPosterSize: "w500",
  nfoBackdropSize: "w1280",
  nfoLogoSize: "w500",
  showLocalLibraryBadge: true,
  localPlaybackMode: "ask",
  localMinFileSizeMb: 50,
  catalogsPinned: [],
  catalogsHidden: [
    "org.sportstors-sports-sports_cats",
    "community.argentinatv-tv-todos",
    "community.cimanow-movie-MCmovies-Arabic",
    "community.cimanow-movie-MCmovies-English",
    "community.cimanow-movie-MCmovies-Indian",
    "community.cimanow-movie-MCmovies-Turkish",
    "community.cimanow-series-MCseries-Arabic",
    "community.cimanow-series-MCseries-English",
    "community.cimanow-series-MCseries-Indian",
    "community.cimanow-series-MCseries-Turkish",
    "community.cimanow-series-MCseries-Asian",
    "pw.ers.netflix-catalog-movie-nfx",
    "pw.ers.netflix-catalog-series-nfx",
    "pw.ers.netflix-catalog-movie-hbm",
    "pw.ers.netflix-catalog-series-hbm",
    "pw.ers.netflix-catalog-movie-dnp",
    "pw.ers.netflix-catalog-series-dnp",
    "pw.ers.netflix-catalog-movie-amp",
    "pw.ers.netflix-catalog-series-amp",
    "pw.ers.netflix-catalog-movie-atp",
    "pw.ers.netflix-catalog-series-atp",
    "org.community.orion-movie-orion.movies",
    "org.community.orion-series-orion.series",
    "community.ppvstreams-tv-basketball",
    "community.ppvstreams-tv-football",
    "community.ppvstreams-tv-Arm Wrestling",
    "community.ppvstreams-tv-Rugby",
    "community.ppvstreams-tv-NFL",
    "community.ppvstreams-tv-Combat Sports",
    "community.ppvstreams-tv-Wrestling",
    "community.ppvstreams-tv-Darts",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-realdebrid_watchlist_movies",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-series-realdebrid_watchlist_series",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-american_football",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-baseball",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-basketball",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-english_hdrip",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-series-english_series",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-football",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-hockey",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-events-live_sport_events",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-tv-live_tv",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-series-motogp_racing",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-other_sports",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-fighting",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-movie-contribution_movies",
    "stremio.addons.mediafusion|elfhostedrd.realdebrid-series-contribution_series",
    "com.keopps.peerflix-other-peerflix-realdebrid",
    "org.stremio.cinemeta-catalogs-halloweenpopular-movie-halloweenpopular",
    "aiostreams.viren070.com.cbd49e0d-a01-other-5614414.torrentio-realdebrid",
    "aiostreams.viren070.com.cbd49e0d-a01-series-a41e3b0.top-series",
    "aiostreams.viren070.com.cbd49e0d-a01-anime-a41e3b0.top-anime",
    "aiostreams.viren070.com.cbd49e0d-a01-other-f4b4414.peerflix-realdebrid",
    "community.usatv-tv-all",
    "com.torrentsdb.addon-other-torrentsdb-realdebrid",
    "com.stremio.torrentio.addon-other-torrentio-realdebrid",
    "com.metegol.live.v5-tv-deportes",
    "com.linvo.cinemeta-movie-imdbRating",
    "com.linvo.cinemeta-series-imdbRating",
    "com.linvo.cinemeta-series-last-videos",
    "com.linvo.cinemeta-series-calendar-videos",
    "aiostreams.viren070.com.cbd49e0d-a01-movie-a41e3b0.top-movies",
  ],
  posterBaseUrl: "",
  hidePosterTitles: false,
  hoverPreviewEnabled: false,
  hoverPreviewPlacement: "over",
  cardHoverStyle: "default",
  customHoverId: "",
  mdblistKey: "",
  auddKey: "",
  aiSearchKey: "",
  aiSearchModel: "",
  aiGroqKey: "",
  jinaKey: "",
  aiWebSearch: false,
  playerD3d11Flip: false,
  mpvExtraOptions: "",
  mpvQuality: "balanced",
  mpvHwdec: "auto",
  mpvBufferBoost: false,
  mpvDownmixStereo: true,
  mpvTweaks: {},
  playerSvp: false,
  svpVpyPath: "",
  svpScope: "all",
  seekBackStepSec: 10,
  seekForwardStepSec: 10,
  playerHdrOpaqueWindow: false,
  playerEscExitsFullscreen: true,
  playerConfirmLeave: true,
  tvNavigation: true,
  playerTvNavigation: false,
  playerHdrStage: "auto",
  opensubtitlesApiKey: "",
  jimakuToken: "",
  audioNormalize: true,
  audioProfile: "voice",
  audioDevice: "",
  bandwidthMbps: 0,
  nextEpisodeLeadSec: -1,
  autoPlayNextEpisode: true,
  keyboardPauseShowsControls: true,
  hideWatchedInCatalogs: false,
  hideUnreleased: false,
  localEpisodeSortDesc: false,
  showPlaylistsTab: false,
  skipProfileScreen: false,
  profilePromptInterval: "launch",
  defaultProfileId: "",
  sportsLeagues: [],
  hideSpoilers: false,
  spoilerHideThumbnails: true,
  spoilerHideTitles: true,
  spoilerHideDescriptions: true,
  spoilerSkipNext: true,
  streamBackdropBlur: true,
  songIdEnabled: true,
  songCardStyle: "compact",
  songCardDetails: true,
  hideContent: {
    anime: false,
    liveTv: false,
    sports: false,
    adult: true,
  },
  theme: {
    preset: "noir",
    backgroundImage: null,
    backgroundDim: 0.22,
    fontPair: "plus-jakarta",
    customFontId: null,
    customColors: {
      canvas: "#1f2128",
      surface: "#292c34",
      elevated: "#34373f",
      raised: "#3f424b",
      ink: "#f6f6f8",
      inkMuted: "#aaadb6",
      inkSubtle: "#6e7079",
      edge: "#70727b",
      accent: "#d3a064",
      danger: "#d35a3a",
    },
  },
  customLogoMark: "",
  customLogoWordmark: "",
  customAppIcon: "",
  homeMode: "harbor",
  homeShowAllAddonRows: true,
  libraryBookmarkedOnly: true,
  librarySort: "recent",
  preferCustomMetaAddon: false,
  animeOnlyInAnimeRoom: false,
  cwAdvanceNext: true,
  useNativeTitleBar: false,
  closeToTray: false,
  trayAlwaysOnTop: false,
  pauseMinimized: true,
  pauseUnfocused: false,
  cwSnapshotRetentionDays: 30,
  cwSnapshotFullQuality: false,
  streamFilterLevel: "strict",
  blockTrackers: true,
  homeRows: {
    order: [],
    hidden: [],
    renamed: {},
    numerals: [],
    heroSource: null,
    customSources: [],
    listRows: [],
  },
  navCustomization: { order: [], hidden: [], renamed: {} },
  hotkeys: {},
  animeFavoriteGenres: [],
  animeExcludeOrigins: ["CN"],
  animeHideWatchedPicks: true,
  animePicksDismissedAt: 0,
  animeAnilistRowsHidden: [],
  animeMalRowsHidden: [],
  pickerLayout: "condensed",
  streamSort: "harbor",
  fullStreamDescription: true,
  pickerShowFilename: false,
  pickerRefreshNextToBack: false,
  customStreamFilters: [],
  seekBarStyle: "flat",
  seekBarHeight: 7,
  seekBarColor: "#ffffff",
  seekBarImage: "",
  seekBarFill: true,
  seekBarFillOpacity: 0.2,
  seekDotShape: "circle",
  seekDotSize: 18,
  seekDotImage: "",
  customCss: "",
  customJs: "",
  customHtml: "",
  webhooks: {
    discordUrl: "",
    telegramUrl: "",
    notifyMovies: true,
    notifyTv: true,
    notifyAnime: true,
    sources: {
      library: true,
      all: false,
      trakt: false,
      anticipated: false,
      custom: false,
    },
  },
  calendarSource: "library",
  simklHomeRailsEnabled: false,
  simklUpNextRailEnabled: false,
  simklTrendingRailEnabled: false,
  simklScrobbleEnabled: true,
  simklAnimeTitleLanguage: "english",
  weekStartsMonday: false,
  customCalendar: {
    trackedPeople: [],
    includeTraktWatchlist: false,
    includeTraktAnticipated: false,
    genres: [],
    watchProviders: [],
    originCountries: [],
    mediaTypes: { movie: true, tv: true, anime: true },
  },
  webhookRules: [],
  downloadDir: "",
  downloadCreateFolders: false,
  stremioDeeplinkInstall: true,
  iptvPlaylists: [],
  iptvLiveContainer: "ts",
  iptvForceProxy: false,
  iptvEpgOffsetHours: 0,
  sidebarCollapsed: true,
  wrappedButton: true,
  feedLocaleBias: true,
  uiLanguage: "en",
  cropMode: "fit",
  customLists: [],
  pauseListStatusOnPause: false,
  translateTitles: false,
  translateDescriptions: true,
  letterboxd: {
    enabled: false,
    mode: "public",
    username: "",
    encodedConfig: "",
    selectedCatalogs: [
      "letterboxd-watchlist",
      "letterboxd-liked",
      "letterboxd-popular",
      "letterboxd-top250",
    ],
    hiddenCatalogs: [],
    catalogOrder: [],
    showRatingsOnPosters: true,
    listRefs: [],
  },
  adSkipEnabled: false,
  adReportAlwaysShow: false,
  adReportFirstSeen: true,
};
